## What is OpenCV?

OpenCV, or Open Source Computer Vision Library, is an open-source computer vision and machine learning software library. It provides a wide range of tools and functions that allow developers to work with images and videos, perform various computer vision tasks, and implement machine learning algorithms.

Key features of OpenCV include:

- Image and Video Processing: OpenCV provides functions for reading, writing, and processing images and videos. It supports various image formats and video codecs.
- Computer Vision Algorithms: OpenCV includes a collection of computer vision algorithms for tasks such as image filtering, edge detection, feature extraction, object recognition, and more.
- Machine Learning Support: OpenCV integrates with machine learning frameworks like TensorFlow and PyTorch, and it includes machine learning tools for tasks such as object detection, facial recognition, and image classification.
- Camera Calibration: OpenCV provides tools for camera calibration, which is essential for computer vision applications that require accurate geometric information.
- Multi-threading: OpenCV supports multi-threading, allowing developers to take advantage of parallel processing for faster execution.
- Cross-platform: OpenCV is cross-platform and can be used on various operating systems, including Windows, Linux, and macOS.

In [2]:
import cv2
import numpy as np

### 1) Loading an Image 

- -1 or cv2.IMREAD_COLOR: Loads a colour image. Any transparency of image will be neglected. It is the default flag
- 0 or cv2.IMREAD_GREYSCALE: Loads image in greyscale mode
- 1 or cv2.IMREAD_UNCHANGED: Loads image as such alpha particle

In [3]:
img=cv2.imread("PV/elon_musk.jpg",-1)

### 2) Displaying the image

In [8]:
cv2.imshow("Image", img)
# cv2.imshow("window_name", image)--- It creates a window to display the image

cv2.waitKey(10000)
# # cv2.waitKey(5)-- wait 5 milliseconds and shut the window
# # cv2.waitKey(0)--waits infinite time and when we press a key, windows shuts

cv2.destroyAllWindows()
# # shuts all window

### 3) Accesing Video 

In [13]:
cap=cv2.VideoCapture("PV/test.mp4")   #  initializes a video capture object (cap) using the default camera (camera index 0)


while True:
    ret, frame = cap.read()  # ret is a boolean indicating whether the frame was successfully read and 'frame' contains the image
    frame=cv2.resize(frame,(640,480))
    cv2.imshow("image", frame)
    
    if cv2.waitKey(1)==ord('q'): # If the key pressed is 'q', the loop is exited, and the program proceeds to the next line
        break
        
cap.release()  # This releases the video capture object, freeing up system resources associated with it
cv2.destroyAllWindows()

### 4) Accessing WebCam

In [14]:
cap=cv2.VideoCapture(0)
cap.set(3,640)  # width
cap.set(4,480)  # height
cap.set(10,100)  # brightness

while True:
    success, vid=cap.read()
    cv2.imshow("Video",vid)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

### 5) Representation of an Image and its Characteristics

In [15]:
print(img)

[[[17 12 11]
  [22 14 14]
  [22 15 12]
  ...
  [ 3  1  1]
  [ 3  1  1]
  [ 2  0  0]]

 [[19 14 13]
  [21 13 13]
  [20 13 10]
  ...
  [ 5  3  3]
  [ 4  2  2]
  [ 3  1  1]]

 [[17 12 11]
  [15 10  9]
  [16  9  6]
  ...
  [ 5  3  3]
  [ 4  2  2]
  [ 3  1  1]]

 ...

 [[23 17 18]
  [17 11 12]
  [11  5  6]
  ...
  [24 16 16]
  [27 19 19]
  [27 19 19]]

 [[17 11 12]
  [15  9 10]
  [14  8  9]
  ...
  [29 21 21]
  [33 25 25]
  [33 25 25]]

 [[15  9 10]
  [15  9 10]
  [16 10 11]
  ...
  [37 30 27]
  [39 32 29]
  [38 31 28]]]


In [16]:
type(img)

numpy.ndarray

Image is actually a numpy array
- OpenCV extracts the pixels from the image and load it in numpy

In [17]:
img.shape

(1197, 907, 3)

shape is (x,y,z)
- x= no. of rows/ height of the image
- y= no. of columns/ width of image
- z= no. of channels - no. of values storing each pixel

- 3 channels is due to the colour- BGR
- standard is RGB but openCV uses BGR,i.e, blue green red
- [x,y,z] pixel represents x amt of blue, y amt. of green and z amt. of red in the pixel
- 0-zero, 255-one.....range is (0-255)
- [255,0,0] represents all blue and none green n red
- [122,0,0] represents some blue and no green n red

### 6) Resize an image

In [20]:
img2=cv2.resize(img,(540,480))
# cv2.resize(img,(len,bredth))

In [21]:
cv2.imshow("Image1",img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
# if you want to double the size then fx=2,fy=2 and if half then fx=0.5,fy=0.5
img3=cv2.resize(img2,(0,0),fx=1.2,fy=1.2)
cv2.imshow("Image1",img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 7) Rotating an Image

In [23]:
img4=cv2.rotate(img2, cv2.ROTATE_90_COUNTERCLOCKWISE)
cv2.imshow("Image1",img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
# Specify the rotation angle (in degrees)
angle = 30

# Get the image dimensions
height, width = img2.shape[:2]

# Calculate the rotation matrix
rotation_matrix = cv2.getRotationMatrix2D((width / 2, height / 2), angle, 1)

# Apply the rotation to the image
rotated_image = cv2.warpAffine(img2, rotation_matrix, (width, height))

# Display the original and rotated images
cv2.imshow("Original Image", img2)
cv2.imshow("Rotated Image", rotated_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

### 8) GrayScale image, blur Image and Canny Image

In [25]:
img = cv2.imread("pv/modi.jpg",-1)
img=cv2.resize(img,(480,480))

imggray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgblur=cv2.GaussianBlur(imggray,(9,9),0)
# imgblur3=cv2.GaussianBlur(imggray,(3,3),0)
imgcanny=cv2.Canny(imggray,100,100)

cv2.imshow("Image Gray",imggray)
cv2.imshow("Image Blur 3",imgblur)
# cv2.imshow("Image Blur 9",imgblur) # increasing number will increase blurness
cv2.imshow("Canny Image",imgcanny)

cv2.waitKey(0)
cv2.destroyAllWindows()

### 9) Adding Shapes and Text to an Image

In [ ]:
img=np.zeros((512,512,3),np.uint8)
cv2.line(img,(0,0),(512,512),(255,0,0),2)
# cv2.line(source image, (starting coordinate), (ending coordinate), (color of line), (thickness of line))
cv2.line(img,(0,512),(512,0),(0,0,255),40)
#cv2.rectangle(img,(100,100),(300,300),(0,255,0),cv2.FILLED)
cv2.rectangle(img,(100,100),(300,300),(0,255,0),2)

cv2.circle(img,(400,400),50,(203, 192, 255),-1)
cv2.putText(img,"OPENCV",(200,400),cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),2)
#putText(source,Text,Starting coordinate,font,font_scale,color,thickness)

In [32]:
cv2.imshow("Image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 10) Real time date n time

In [1]:
import cv2
import datetime as dt

cap=cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    date_time=str(dt.datetime.now())
    frame=cv2.putText(frame,date_time,(10,50),cv2.FONT_HERSHEY_SIMPLEX,1,(255,0,0),2,cv2.LINE_AA)
    cv2.imshow("Video",frame)
    if cv2.waitKey(1)==ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

### 11) Handle Mouse Events

In [2]:
import cv2
import numpy as np

# Create a black image
img = np.zeros((512, 512, 3), np.uint8)

# Display the image to create the window
cv2.imshow('image', img)
cv2.waitKey(1)  # Needed to create the window

# Initialize variables for coordinates
coordinates = ""

# Define the mouse callback function using a lambda function
cv2.setMouseCallback('image', lambda event, x, y, flags, param:
    [print(f'Mouse event: {event}, Coordinates: ({x}, {y})'),
     (cv2.putText(img, f'{x},{y}', (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 0, 0), 2, cv2.LINE_AA) if event == cv2.EVENT_LBUTTONDOWN else None)][-1])

# Main loop
while True:
    cv2.imshow('image', img)
    if cv2.waitKey(1) == ord("q"):
        break

cv2.destroyAllWindows()

Mouse event: 0, Coordinates: (212, 507)
Mouse event: 0, Coordinates: (212, 507)
Mouse event: 0, Coordinates: (212, 507)
Mouse event: 0, Coordinates: (218, 495)
Mouse event: 0, Coordinates: (233, 468)
Mouse event: 0, Coordinates: (240, 455)
Mouse event: 0, Coordinates: (245, 446)
Mouse event: 0, Coordinates: (254, 432)
Mouse event: 0, Coordinates: (263, 414)
Mouse event: 0, Coordinates: (275, 396)
Mouse event: 0, Coordinates: (282, 384)
Mouse event: 0, Coordinates: (292, 369)
Mouse event: 0, Coordinates: (299, 359)
Mouse event: 0, Coordinates: (309, 346)
Mouse event: 0, Coordinates: (316, 336)
Mouse event: 0, Coordinates: (320, 330)
Mouse event: 0, Coordinates: (324, 324)
Mouse event: 0, Coordinates: (328, 319)
Mouse event: 0, Coordinates: (330, 313)
Mouse event: 0, Coordinates: (331, 310)
Mouse event: 0, Coordinates: (333, 308)
Mouse event: 0, Coordinates: (333, 307)
Mouse event: 0, Coordinates: (333, 306)
Mouse event: 0, Coordinates: (334, 304)
Mouse event: 0, Coordinates: (334, 303)


### 12) Merge Image

In [3]:
import cv2
import numpy as np

# Read two images
image1 = cv2.imread('PV/modi.jpg')
image2 = cv2.imread('pV/linkedin.jpg')

# Ensure that both images have the same height
rows, _, _ = image1.shape
image2 = cv2.resize(image2, (int(image2.shape[1] * rows / image2.shape[0]), rows))

# Resize the first image to match the width of the second image
image1 = cv2.resize(image1, (image2.shape[1], rows))

# Merge images
merged_image = np.concatenate((image1, image2), axis=1)

# Display the merged image
cv2.imshow('Merged Image', merged_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 13) Split the image

In [4]:
import cv2
import numpy as np

# Read two images
image1 = cv2.imread('PV/modi.jpg')
image2 = cv2.imread('PV/linkedin.jpg')

# Ensure that both images have the same height
rows, _, _ = image1.shape
image2 = cv2.resize(image2, (int(image2.shape[1] * rows / image2.shape[0]), rows))

# Resize the first image to match the width of the second image
image1 = cv2.resize(image1, (image2.shape[1], rows))

# Merge images
merged_image = np.concatenate((image1, image2), axis=1)

# Split the merged image into two parts
split1, split2= np.split(merged_image, 2, axis=1)

# Display the split images
cv2.imshow('Split Image 1', split1)
cv2.imshow('Split Image 2', split2)
cv2.waitKey(0)
cv2.destroyAllWindows()